// Code generated by mockery. DO NOT EDIT.
// template: wrappers/space.gotmpl

package middleware

import (
	"context"
	"fmt"

	"github.com/breml/mockery-wrap-test/pkg"
)

// ExamplerWithSpace implements pkg.Exampler that is instrumented with space.
type ExamplerWithSpace struct {
	_base pkg.Exampler
	space string
}

// NewExamplerWithSpace instruments an implementation of the pkg.Exampler with space.
func NewExamplerWithSpace(base pkg.Exampler, space string) ExamplerWithSpace {
	return ExamplerWithSpace{
		_base: base,
		space: space,
	}
}

// Example implements pkg.Exampler.
func (_d ExamplerWithSpace) Example() {

	defer func() {
		fmt.Println(_d.space)
	}()

	_d._base.Example()
}

// ExampleWithArgs implements pkg.Exampler.
func (_d ExamplerWithSpace) ExampleWithArgs(arg0 int, arg1 string) {

	defer func() {
		fmt.Println(_d.space)
	}()

	_d._base.ExampleWithArgs(arg0, arg1)
}

// ExampleWithArgsAndVariadicArgs implements pkg.Exampler.
func (_d ExamplerWithSpace) ExampleWithArgsAndVariadicArgs(arg0 int, args ...string) {

	defer func() {
		fmt.Println(_d.space)
	}()

	_d._base.ExampleWithArgsAndVariadicArgs(arg0, args...)
}

// ExampleWithContext implements pkg.Exampler.
func (_d ExamplerWithSpace) ExampleWithContext(ctx context.Context) {

	defer func() {
		fmt.Println(_d.space)
	}()

	_d._base.ExampleWithContext(ctx)
}

// ExampleWithContextAndArgs implements pkg.Exampler.
func (_d ExamplerWithSpace) ExampleWithContextAndArgs(ctx context.Context, arg0 int, arg1 string) {

	defer func() {
		fmt.Println(_d.space)
	}()

	_d._base.ExampleWithContextAndArgs(ctx, arg0, arg1)
}

// ExampleWithContextArgsAndVariadicArgs implements pkg.Exampler.
func (_d ExamplerWithSpace) ExampleWithContextArgsAndVariadicArgs(ctx context.Context, arg0 int, args ...string) {

	defer func() {
		fmt.Println(_d.space)
	}()

	_d._base.ExampleWithContextArgsAndVariadicArgs(ctx, arg0, args...)
}

// ExampleWithErrorReturn implements pkg.Exampler.
func (_d ExamplerWithSpace) ExampleWithErrorReturn() (err error) {

	defer func() {
		fmt.Println(_d.space)
	}()

	return _d._base.ExampleWithErrorReturn()
}

// ExampleWithReturn implements pkg.Exampler.
func (_d ExamplerWithSpace) ExampleWithReturn() (s string) {

	defer func() {
		fmt.Println(_d.space)
	}()

	return _d._base.ExampleWithReturn()
}

// ExampleWithReturnAndError implements pkg.Exampler.
func (_d ExamplerWithSpace) ExampleWithReturnAndError() (s string, err error) {

	defer func() {
		fmt.Println(_d.space)
	}()

	return _d._base.ExampleWithReturnAndError()
}

// ExampleWithVariadicArgs implements pkg.Exampler.
func (_d ExamplerWithSpace) ExampleWithVariadicArgs(args ...string) {

	defer func() {
		fmt.Println(_d.space)
	}()

	_d._base.ExampleWithVariadicArgs(args...)
}

// FullExample implements pkg.Exampler.
func (_d ExamplerWithSpace) FullExample(ctx context.Context, arg0 int, arg1 string, args ...string) (s string, err error) {

	defer func() {
		fmt.Println(_d.space)
	}()

	return _d._base.FullExample(ctx, arg0, arg1, args...)
}
